import pandas as pd
import sys
from pathlib import Path
import os

BASE_DIR = Path("/Users/alisaglam/TezaverMac")
COIN_CELLS = BASE_DIR / "coin_cells"
OUT_DIR = BASE_DIR / "output/global_audit"
OUT_DIR.mkdir(parents=True, exist_ok=True)

# Priority: Run 003 > Run 002 > Run 001
def get_best_report(symbol):
    base = COIN_CELLS / symbol / "output/kader_v3_fixed/runs"
    r3 = base / "run_003/reports" / f"{symbol}_NET_ADAY_REPORT.csv"
    r2 = base / "run_002/reports" / f"{symbol}_NET_ADAY_REPORT.csv"
    r1 = base / "run_001/reports" / f"{symbol}_NET_ADAY_REPORT.csv"
    
    if r3.exists(): return r3
    if r2.exists(): return r2
    if r1.exists(): return r1
    return None

COINS = [
    "0GUSDT", "1000CATUSDT", "1000CHEEMSUSDT", "1000SATSUSDT", 
    "1INCHUSDT", "1MBABYDOGEUSDT", "AAVEUSDT", "ACAUSDT"
]

def generate_report():
    all_rows = []
    
    for symbol in COINS:
        rep = get_best_report(symbol)
        if rep:
            try:
                df = pd.read_csv(rep)
                if len(df) == 0: continue
                
                # Standardize columns
                # Need: Date, Symbol, Max_Excursion, Drawdown, Close_Excursion
                cols = ['Date', 'Symbol', 'Max_Excursion', 'Drawdown', 'Close_Excursion']
                sub = df[cols].copy()
                all_rows.append(sub)
            except Exception as e:
                print(f"Error loading {symbol}: {e}")
                
    if not all_rows:
        print("No data found.")
        return
        
    full_df = pd.concat(all_rows)
    # Simplify Date
    full_df['Date'] = full_df['Date'].apply(lambda x: x[:10])
    
    # Sort
    full_df.sort_values(by=['Date', 'Symbol'], inplace=True)
    
    # Group By Date
    unique_dates = full_df['Date'].unique()
    
    md = "# 📅 DAILY PnL BREAKDOWN (10-Coin Pilot)\n\n"
    md += "Performance metrics for all signals generated by the final Logic configuration for each coin.\n\n"
    md += "- **Max Gain:** `Max_Excursion` (Best profit potential in 24h)\n"
    md += "- **Max Loss:** `Drawdown` (Worst loss potential in 24h)\n"
    md += "- **Close PnL:** `Close_Excursion` (Profit/Loss at 24h close)\n\n"
    
    total_signals = 0
    total_hits = 0
    
    for d in unique_dates:
        day_df = full_df[full_df['Date'] == d]
        
        md += f"## 🗓 {d}\n"
        md += f"**Signals:** {len(day_df)}\n\n"
        
        md += "| Coin | Max Gain (%) | Max Loss (%) | Close PnL (%) | Result |\n"
        md += "|---|---|---|---|---|\n"
        
        day_gain = 0
        day_loss = 0
        
        for _, row in day_df.iterrows():
            gain = row['Max_Excursion']
            loss = row['Drawdown']
            close = row['Close_Excursion']
            
            res = "❌ FAIL"
            if gain >= 10.0:
                res = "✅ HIT (+10%)"
                total_hits += 1
            
            md += f"| {row['Symbol']} | **+{gain:.2f}%** | {loss:.2f}% | {close:.2f}% | {res} |\n"
            
        total_signals += len(day_df)
        md += "\n"
        
    md += "## 📊 SUMMARY\n"
    md += f"- **Total Signals:** {total_signals}\n"
    md += f"- **Total Hits (>=10%):** {total_hits}\n"
    if total_signals > 0:
        md += f"- **Overall Win Rate:** {total_hits/total_signals*100:.1f}%\n"
        
    with open(OUT_DIR / "DAILY_PNL_BREAKDOWN.md", "w") as f:
        f.write(md)
    
    print(md)

if __name__ == "__main__":
    generate_report()
