"""
Pool Models V1
==============

Data models for the Matrix Pool Engine (Phase 2A).
Includes Universe, Tick, and Intent definitions.
"""
from dataclasses import dataclass, field
from typing import List, Dict, Optional, Any

@dataclass
class PoolUniverseCellV1:
    """Represents a single executable cell (symbol+timeframe) in the pool universe."""
    symbol: str
    timeframe: str
    bundles_loaded_ok: List[str]  # List of bundle_ids
    best_bundle_id: Optional[str] = None
    qc_score_best: Optional[int] = None
    tier_best: Optional[str] = None

@dataclass
class PoolUniverseReportV1:
    """Report generated after building the pool universe."""
    run_id: str
    stage: str
    engine_version: str
    data_fingerprint: str
    config_signature: str
    built_ts_iso: str
    cells_total: int
    cells_by_tf: Dict[str, int]
    cells: List[PoolUniverseCellV1]
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "run_id": self.run_id,
            "stage": self.stage,
            "engine_version": self.engine_version,
            "data_fingerprint": self.data_fingerprint,
            "config_signature": self.config_signature,
            "built_ts_iso": self.built_ts_iso,
            "cells_total": self.cells_total,
            "cells_by_tf": self.cells_by_tf,
            "cells": [
                {
                    "symbol": c.symbol,
                    "timeframe": c.timeframe,
                    "bundles_loaded_ok": c.bundles_loaded_ok,
                    "best_bundle_id": c.best_bundle_id,
                    "qc_score_best": c.qc_score_best,
                    "tier_best": c.tier_best
                } for c in self.cells
            ]
        }

@dataclass
class PoolTickReportV1:
    """Report generated for each pool engine tick."""
    run_id: str
    stage: str
    engine_version: str
    data_fingerprint: str
    config_signature: str
    tick_ts_iso: str
    tick_reason: str # e.g. "BAR_CLOSED"
    closed_bars: Dict[str, str] # timeframe -> bar_ts_iso
    intents_considered: int
    intents_created: int
    intents_skipped: int
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "run_id": self.run_id,
            "stage": self.stage,
            "engine_version": self.engine_version,
            "data_fingerprint": self.data_fingerprint,
            "config_signature": self.config_signature,
            "tick_ts_iso": self.tick_ts_iso,
            "tick_reason": self.tick_reason,
            "closed_bars": self.closed_bars,
            "intents_considered": self.intents_considered,
            "intents_created": self.intents_created,
            "intents_skipped": self.intents_skipped
        }

@dataclass
class TradeIntentV1:
    """Deterministic trade intent generated by the pool engine."""
    intent_id: str
    symbol: str
    timeframe: str
    bundle_id: str
    trigger_type: str
    exit_policy: str
    created_ts_iso: str
    reason: str # "OK", "SKIPPED_..."
    qc_score: int
    proposed_notional: float = 0.0
    tier: Optional[str] = None
    entry_ts_iso: Optional[str] = None
    scenario_id: Optional[str] = None
    narrative: Optional[Dict[str, Any]] = None
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "intent_id": self.intent_id,
            "symbol": self.symbol,
            "timeframe": self.timeframe,
            "bundle_id": self.bundle_id,
            "trigger_type": self.trigger_type,
            "exit_policy": self.exit_policy,
            "created_ts_iso": self.created_ts_iso,
            "reason": self.reason,
            "qc_score": self.qc_score,
            "proposed_notional": self.proposed_notional,
            "tier": self.tier,
            "entry_ts_iso": self.entry_ts_iso,
            "scenario_id": self.scenario_id,
            "narrative": self.narrative
        }

@dataclass
class PoolIntentsReportV1:
    """Report containing all generated intents for a tick/run."""
    run_id: str
    stage: str
    engine_version: str
    data_fingerprint: str
    config_signature: str
    built_ts_iso: str
    intents_total: int
    intents_created: int
    intents_skipped: int
    intents: List[TradeIntentV1]
    skipped_reasons_count: Dict[str, int]
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "run_id": self.run_id,
            "stage": self.stage,
            "engine_version": self.engine_version,
            "data_fingerprint": self.data_fingerprint,
            "config_signature": self.config_signature,
            "built_ts_iso": self.built_ts_iso,
            "intents_total": self.intents_total,
            "intents_created": self.intents_created,
            "intents_skipped": self.intents_skipped,
            "intents": [i.to_dict() for i in self.intents],
            "skipped_reasons_count": self.skipped_reasons_count
        }

@dataclass
class PoolPortfolioSnapshotV1:
    """Snapshot of open positions and capacity check."""
    run_id: str
    stage: str
    engine_version: str
    data_fingerprint: str
    config_signature: str
    built_ts_iso: str
    max_open_positions: int
    open_now: int
    capacity: int
    open_positions: List[Dict[str, Any]] # Minimal Position info
    source: str # e.g. "provider:stub"

    def to_dict(self) -> Dict[str, Any]:
        return {
            "run_id": self.run_id,
            "stage": self.stage,
            "engine_version": self.engine_version,
            "data_fingerprint": self.data_fingerprint,
            "config_signature": self.config_signature,
            "built_ts_iso": self.built_ts_iso,
            "max_open_positions": self.max_open_positions,
            "open_now": self.open_now,
            "capacity": self.capacity,
            "open_positions": self.open_positions,
            "source": self.source
        }

@dataclass
class PoolSelectionItemV1:
    """An intent that has been evaluated for selection."""
    intent_id: str
    symbol: str
    timeframe: str
    bundle_id: str
    qc_score: int
    tier: Optional[str]
    trigger_type: str
    exit_policy: str
    proposed_notional: float
    rank_score: float
    rank_reason: str # "qc+tier"
    scenario_id: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        return {
            "intent_id": self.intent_id,
            "symbol": self.symbol,
            "timeframe": self.timeframe,
            "bundle_id": self.bundle_id,
            "qc_score": self.qc_score,
            "proposed_notional": self.proposed_notional,
            "tier": self.tier,
            "trigger_type": self.trigger_type,
            "exit_policy": self.exit_policy,
            "rank_score": self.rank_score,
            "rank_reason": self.rank_reason,
            "scenario_id": self.scenario_id
        }

@dataclass
class PoolSelectionReportV1:
    """Report on the selection process."""
    run_id: str
    stage: str
    engine_version: str
    data_fingerprint: str
    config_signature: str
    built_ts_iso: str
    max_open_positions: int
    open_now: int
    capacity: int
    intents_considered: int
    intents_eligible: int # reason=="OK"
    selected_count: int
    skipped_count: int
    skipped_reasons_count: Dict[str, int]
    selected: List[PoolSelectionItemV1]
    skipped: List[Dict[str, str]] # {"intent_id":..., "reason":...}
    selection_policy_v1: Dict[str, Any] # Algo config

    def to_dict(self) -> Dict[str, Any]:
        return {
            "run_id": self.run_id,
            "stage": self.stage,
            "engine_version": self.engine_version,
            "data_fingerprint": self.data_fingerprint,
            "config_signature": self.config_signature,
            "built_ts_iso": self.built_ts_iso,
            "max_open_positions": self.max_open_positions,
            "open_now": self.open_now,
            "capacity": self.capacity,
            "intents_considered": self.intents_considered,
            "intents_eligible": self.intents_eligible,
            "selected_count": self.selected_count,
            "skipped_count": self.skipped_count,
            "skipped_reasons_count": self.skipped_reasons_count,
            "selected": [s.to_dict() for s in self.selected],
            "skipped": self.skipped,
            "selection_policy_v1": self.selection_policy_v1
        }

# ============================================================
# Phase 2C: Risk and Execution Models
# ============================================================

@dataclass
class PoolRiskItemV1:
    """Risk evaluation for a single selected intent."""
    intent_id: str
    symbol: str
    timeframe: str
    bundle_id: str
    qc_score: int
    tier: Optional[str]
    proposed_notional: float
    risk_units: float  # Normalized risk measure
    stop_type: str     # "ATR"|"FIXED"|"TRAILING"|"NONE"
    stop_value: Optional[float]
    risk_flags: List[str]
    verdict: str       # "ALLOW"|"BLOCK"
    block_reason: Optional[str]

    def to_dict(self) -> Dict[str, Any]:
        return {
            "intent_id": self.intent_id,
            "symbol": self.symbol,
            "timeframe": self.timeframe,
            "bundle_id": self.bundle_id,
            "qc_score": self.qc_score,
            "tier": self.tier,
            "proposed_notional": self.proposed_notional,
            "risk_units": self.risk_units,
            "stop_type": self.stop_type,
            "stop_value": self.stop_value,
            "risk_flags": self.risk_flags,
            "verdict": self.verdict,
            "block_reason": self.block_reason
        }

@dataclass
class PoolRiskReportV1:
    """Report on risk evaluation for selected intents."""
    run_id: str
    stage: str
    engine_version: str
    data_fingerprint: str
    config_signature: str
    built_ts_iso: str
    selection_run_id: str
    selected_count: int
    allowed_count: int
    blocked_count: int
    total_proposed_notional: float
    total_allowed_notional: float
    global_limits: Dict[str, Any]
    kill_switch: Dict[str, Any]
    risk_limiter: Dict[str, Any]
    items: List[PoolRiskItemV1]
    blocked_reasons_count: Dict[str, int]

    def to_dict(self) -> Dict[str, Any]:
        return {
            "run_id": self.run_id,
            "stage": self.stage,
            "engine_version": self.engine_version,
            "data_fingerprint": self.data_fingerprint,
            "config_signature": self.config_signature,
            "built_ts_iso": self.built_ts_iso,
            "selection_run_id": self.selection_run_id,
            "selected_count": self.selected_count,
            "allowed_count": self.allowed_count,
            "blocked_count": self.blocked_count,
            "total_proposed_notional": self.total_proposed_notional,
            "total_allowed_notional": self.total_allowed_notional,
            "global_limits": self.global_limits,
            "kill_switch": self.kill_switch,
            "risk_limiter": self.risk_limiter,
            "items": [i.to_dict() for i in self.items],
            "blocked_reasons_count": self.blocked_reasons_count
        }

@dataclass
class PoolExecutionPlanItemV1:
    """Execution plan for a single intent (dry-run)."""
    intent_id: str
    symbol: str
    timeframe: str
    bundle_id: str
    action: str        # "PLACE_ORDER"|"SKIP_BLOCKED"
    side: str          # "BUY"
    order_type: str    # "MARKET"
    notional: float
    policy_exit: str   # ATR/FIXED/TRAILING
    notes: List[str]

    def to_dict(self) -> Dict[str, Any]:
        return {
            "intent_id": self.intent_id,
            "symbol": self.symbol,
            "timeframe": self.timeframe,
            "bundle_id": self.bundle_id,
            "action": self.action,
            "side": self.side,
            "order_type": self.order_type,
            "notional": self.notional,
            "policy_exit": self.policy_exit,
            "notes": self.notes
        }

@dataclass
class PoolExecutionSummaryV1:
    """Execution summary report (dry-run)."""
    run_id: str
    stage: str
    engine_version: str
    data_fingerprint: str
    config_signature: str
    built_ts_iso: str
    selection_run_id: str
    risk_run_id: str
    planned_orders: int
    skipped_orders: int
    planned_total_notional: float
    per_timeframe_counts: Dict[str, int]
    per_tier_counts: Dict[str, int]
    plan: List[PoolExecutionPlanItemV1]
    mode: str  # "DRY_RUN"

    def to_dict(self) -> Dict[str, Any]:
        return {
            "run_id": self.run_id,
            "stage": self.stage,
            "engine_version": self.engine_version,
            "data_fingerprint": self.data_fingerprint,
            "config_signature": self.config_signature,
            "built_ts_iso": self.built_ts_iso,
            "selection_run_id": self.selection_run_id,
            "risk_run_id": self.risk_run_id,
            "planned_orders": self.planned_orders,
            "skipped_orders": self.skipped_orders,
            "planned_total_notional": self.planned_total_notional,
            "per_timeframe_counts": self.per_timeframe_counts,
            "per_tier_counts": self.per_tier_counts,
            "plan": [p.to_dict() for p in self.plan],
            "mode": self.mode
        }

# ============================================================
# Phase 2D: Arm State and Reconcile Models
# ============================================================

@dataclass
class LiveArmStateReportV1:
    """LIVE arm state report for durability proof."""
    run_id: str
    stage: str
    engine_version: str
    data_fingerprint: str
    config_signature: str
    built_ts_iso: str
    arm_id: str
    armed: bool
    arm_reason: str  # "BUNDLE_ARMED"|"MANUAL_ARM"|"DISARMED"
    bundle_id: Optional[str]
    symbol: Optional[str]
    timeframe: Optional[str]
    qc_score: Optional[int]
    tier: Optional[str]
    notes: List[str]

    def to_dict(self) -> Dict[str, Any]:
        return {
            "run_id": self.run_id,
            "stage": self.stage,
            "engine_version": self.engine_version,
            "data_fingerprint": self.data_fingerprint,
            "config_signature": self.config_signature,
            "built_ts_iso": self.built_ts_iso,
            "arm_id": self.arm_id,
            "armed": self.armed,
            "arm_reason": self.arm_reason,
            "bundle_id": self.bundle_id,
            "symbol": self.symbol,
            "timeframe": self.timeframe,
            "qc_score": self.qc_score,
            "tier": self.tier,
            "notes": self.notes
        }

@dataclass
class RestartReconcileReportV1:
    """Restart reconcile report for drift detection."""
    run_id: str
    stage: str
    engine_version: str
    data_fingerprint: str
    config_signature: str
    built_ts_iso: str
    reconcile_id: str
    before: Dict[str, Any]  # {"open_positions_count": int, "positions": list}
    after: Dict[str, Any]   # {"open_positions_count": int, "positions": list}
    drift: Dict[str, Any]   # {"changed": bool, "delta_count": int, "missing_ids": list, "extra_ids": list}
    source: Dict[str, Any]  # {"provider": str, "details": str}
    verdict: str            # "OK"|"NEEDS_SAFE_MODE"
    suggested_actions: List[str]

    def to_dict(self) -> Dict[str, Any]:
        return {
            "run_id": self.run_id,
            "stage": self.stage,
            "engine_version": self.engine_version,
            "data_fingerprint": self.data_fingerprint,
            "config_signature": self.config_signature,
            "built_ts_iso": self.built_ts_iso,
            "reconcile_id": self.reconcile_id,
            "before": self.before,
            "after": self.after,
            "drift": self.drift,
            "source": self.source,
            "verdict": self.verdict,
            "suggested_actions": self.suggested_actions
        }

# ============================================================
# Phase 3B: Replacement Models
# ============================================================

@dataclass
class PoolReplacementCandidateV1:
    """Replacement candidate details."""
    replace_out_pos_id: str
    replace_out_symbol: str
    replace_out_timeframe: Optional[str]
    replace_out_score: float
    replace_in_intent_id: str
    replace_in_symbol: str
    replace_in_timeframe: str
    replace_in_bundle_id: str
    replace_in_rank_score: float
    delta_score: float
    reason: str  # "BONUS_BETTER_THAN_WORST"
    requires_human_confirm: bool

    def to_dict(self) -> Dict[str, Any]:
        return {
            "replace_out_pos_id": self.replace_out_pos_id,
            "replace_out_symbol": self.replace_out_symbol,
            "replace_out_timeframe": self.replace_out_timeframe,
            "replace_out_score": self.replace_out_score,
            "replace_in_intent_id": self.replace_in_intent_id,
            "replace_in_symbol": self.replace_in_symbol,
            "replace_in_timeframe": self.replace_in_timeframe,
            "replace_in_bundle_id": self.replace_in_bundle_id,
            "replace_in_rank_score": self.replace_in_rank_score,
            "delta_score": self.delta_score,
            "reason": self.reason,
            "requires_human_confirm": self.requires_human_confirm
        }

@dataclass
class PoolReplacementReportV1:
    """Replacement analysis report."""
    run_id: str
    stage: str
    engine_version: str
    data_fingerprint: str
    config_signature: str
    built_ts_iso: str
    enabled: bool
    capacity: int
    open_now: int
    max_open_positions: int
    considered_intents: int
    verdict: str  # "NONE"|"SUGGESTED"|"SKIPPED"
    skip_reason: Optional[str]  # "DISABLED"|"CAPACITY_AVAILABLE"|...
    candidate: Optional[PoolReplacementCandidateV1]

    def to_dict(self) -> Dict[str, Any]:
        return {
            "run_id": self.run_id,
            "stage": self.stage,
            "engine_version": self.engine_version,
            "data_fingerprint": self.data_fingerprint,
            "config_signature": self.config_signature,
            "built_ts_iso": self.built_ts_iso,
            "enabled": self.enabled,
            "capacity": self.capacity,
            "open_now": self.open_now,
            "max_open_positions": self.max_open_positions,
            "considered_intents": self.considered_intents,
            "verdict": self.verdict,
            "skip_reason": self.skip_reason,
            "candidate": self.candidate.to_dict() if self.candidate else None
        }

# ============================================================
# Phase 3C: Replacement Plan Models
# ============================================================

@dataclass
class PoolClosePlanItemV1:
    """Plan item for closing a position."""
    action: str  # "CLOSE_POSITION"
    pos_id: str
    symbol: str
    close_mode: str  # "MARKET_DRYRUN"|"LIMIT_DRYRUN"
    reason: str
    notes: List[str]

    def to_dict(self) -> Dict[str, Any]:
        return {
            "action": self.action,
            "pos_id": self.pos_id,
            "symbol": self.symbol,
            "close_mode": self.close_mode,
            "reason": self.reason,
            "notes": self.notes
        }

@dataclass
class PoolOpenPlanItemV1:
    """Plan item for opening a position."""
    action: str  # "OPEN_POSITION"
    intent_id: str
    bundle_id: str
    symbol: str
    timeframe: str
    notional: float
    open_mode: str  # "MARKET_DRYRUN"|"LIMIT_DRYRUN"
    policy_spec: Optional[Dict[str, Any]]
    notes: List[str]

    def to_dict(self) -> Dict[str, Any]:
        return {
            "action": self.action,
            "intent_id": self.intent_id,
            "bundle_id": self.bundle_id,
            "symbol": self.symbol,
            "timeframe": self.timeframe,
            "notional": self.notional,
            "open_mode": self.open_mode,
            "policy_spec": self.policy_spec,
            "notes": self.notes
        }

@dataclass
class PoolReplacementPlanReportV1:
    """Atomic replacement plan report."""
    run_id: str
    stage: str
    engine_version: str
    data_fingerprint: str
    config_signature: str
    built_ts_iso: str
    enabled: bool
    replacement_verdict: str  # "NONE"|"SUGGESTED"|"SKIPPED"
    requires_human_confirm: bool
    close_plan: Optional[PoolClosePlanItemV1]
    open_plan: Optional[PoolOpenPlanItemV1]
    atomic_order: List[str]  # ["CLOSE_POSITION","OPEN_POSITION"]
    skip_reason: Optional[str]

    def to_dict(self) -> Dict[str, Any]:
        return {
            "run_id": self.run_id,
            "stage": self.stage,
            "engine_version": self.engine_version,
            "data_fingerprint": self.data_fingerprint,
            "config_signature": self.config_signature,
            "built_ts_iso": self.built_ts_iso,
            "enabled": self.enabled,
            "replacement_verdict": self.replacement_verdict,
            "requires_human_confirm": self.requires_human_confirm,
            "close_plan": self.close_plan.to_dict() if self.close_plan else None,
            "open_plan": self.open_plan.to_dict() if self.open_plan else None,
            "atomic_order": self.atomic_order,
            "skip_reason": self.skip_reason
        }
