"""
Pool Models V1
==============

Data models for the Matrix Pool Engine (Phase 2A).
Includes Universe, Tick, and Intent definitions.
"""
from dataclasses import dataclass, field
from typing import List, Dict, Optional, Any

@dataclass
class PoolUniverseCellV1:
    """Represents a single executable cell (symbol+timeframe) in the pool universe."""
    symbol: str
    timeframe: str
    bundles_loaded_ok: List[str]  # List of bundle_ids
    best_bundle_id: Optional[str] = None
    qc_score_best: Optional[int] = None
    tier_best: Optional[str] = None

@dataclass
class PoolUniverseReportV1:
    """Report generated after building the pool universe."""
    run_id: str
    stage: str
    engine_version: str
    data_fingerprint: str
    config_signature: str
    built_ts_iso: str
    cells_total: int
    cells_by_tf: Dict[str, int]
    cells: List[PoolUniverseCellV1]
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "run_id": self.run_id,
            "stage": self.stage,
            "engine_version": self.engine_version,
            "data_fingerprint": self.data_fingerprint,
            "config_signature": self.config_signature,
            "built_ts_iso": self.built_ts_iso,
            "cells_total": self.cells_total,
            "cells_by_tf": self.cells_by_tf,
            "cells": [
                {
                    "symbol": c.symbol,
                    "timeframe": c.timeframe,
                    "bundles_loaded_ok": c.bundles_loaded_ok,
                    "best_bundle_id": c.best_bundle_id,
                    "qc_score_best": c.qc_score_best,
                    "tier_best": c.tier_best
                } for c in self.cells
            ]
        }

@dataclass
class PoolTickReportV1:
    """Report generated for each pool engine tick."""
    run_id: str
    stage: str
    engine_version: str
    data_fingerprint: str
    config_signature: str
    tick_ts_iso: str
    tick_reason: str # e.g. "BAR_CLOSED"
    closed_bars: Dict[str, str] # timeframe -> bar_ts_iso
    intents_considered: int
    intents_created: int
    intents_skipped: int
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "run_id": self.run_id,
            "stage": self.stage,
            "engine_version": self.engine_version,
            "data_fingerprint": self.data_fingerprint,
            "config_signature": self.config_signature,
            "tick_ts_iso": self.tick_ts_iso,
            "tick_reason": self.tick_reason,
            "closed_bars": self.closed_bars,
            "intents_considered": self.intents_considered,
            "intents_created": self.intents_created,
            "intents_skipped": self.intents_skipped
        }

@dataclass
class TradeIntentV1:
    """Deterministic trade intent generated by the pool engine."""
    intent_id: str
    symbol: str
    timeframe: str
    bundle_id: str
    trigger_type: str
    exit_policy: str
    created_ts_iso: str
    reason: str # "OK", "SKIPPED_..."
    qc_score: int
    tier: Optional[str] = None
    entry_ts_iso: Optional[str] = None
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "intent_id": self.intent_id,
            "symbol": self.symbol,
            "timeframe": self.timeframe,
            "bundle_id": self.bundle_id,
            "trigger_type": self.trigger_type,
            "exit_policy": self.exit_policy,
            "created_ts_iso": self.created_ts_iso,
            "reason": self.reason,
            "qc_score": self.qc_score,
            "tier": self.tier,
            "entry_ts_iso": self.entry_ts_iso
        }

@dataclass
class PoolIntentsReportV1:
    """Report containing all generated intents for a tick/run."""
    run_id: str
    stage: str
    engine_version: str
    data_fingerprint: str
    config_signature: str
    built_ts_iso: str
    intents_total: int
    intents_created: int
    intents_skipped: int
    intents: List[TradeIntentV1]
    skipped_reasons_count: Dict[str, int]
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "run_id": self.run_id,
            "stage": self.stage,
            "engine_version": self.engine_version,
            "data_fingerprint": self.data_fingerprint,
            "config_signature": self.config_signature,
            "built_ts_iso": self.built_ts_iso,
            "intents_total": self.intents_total,
            "intents_created": self.intents_created,
            "intents_skipped": self.intents_skipped,
            "intents": [i.to_dict() for i in self.intents],
            "skipped_reasons_count": self.skipped_reasons_count
        }

@dataclass
class PoolPortfolioSnapshotV1:
    """Snapshot of open positions and capacity check."""
    run_id: str
    stage: str
    engine_version: str
    data_fingerprint: str
    config_signature: str
    built_ts_iso: str
    max_open_positions: int
    open_now: int
    capacity: int
    open_positions: List[Dict[str, Any]] # Minimal Position info
    source: str # e.g. "provider:stub"

    def to_dict(self) -> Dict[str, Any]:
        return {
            "run_id": self.run_id,
            "stage": self.stage,
            "engine_version": self.engine_version,
            "data_fingerprint": self.data_fingerprint,
            "config_signature": self.config_signature,
            "built_ts_iso": self.built_ts_iso,
            "max_open_positions": self.max_open_positions,
            "open_now": self.open_now,
            "capacity": self.capacity,
            "open_positions": self.open_positions,
            "source": self.source
        }

@dataclass
class PoolSelectionItemV1:
    """An intent that has been evaluated for selection."""
    intent_id: str
    symbol: str
    timeframe: str
    bundle_id: str
    qc_score: int
    tier: Optional[str]
    trigger_type: str
    exit_policy: str
    rank_score: float
    rank_reason: str # "qc+tier"

    def to_dict(self) -> Dict[str, Any]:
        return {
            "intent_id": self.intent_id,
            "symbol": self.symbol,
            "timeframe": self.timeframe,
            "bundle_id": self.bundle_id,
            "qc_score": self.qc_score,
            "tier": self.tier,
            "trigger_type": self.trigger_type,
            "exit_policy": self.exit_policy,
            "rank_score": self.rank_score,
            "rank_reason": self.rank_reason
        }

@dataclass
class PoolSelectionReportV1:
    """Report on the selection process."""
    run_id: str
    stage: str
    engine_version: str
    data_fingerprint: str
    config_signature: str
    built_ts_iso: str
    max_open_positions: int
    open_now: int
    capacity: int
    intents_considered: int
    intents_eligible: int # reason=="OK"
    selected_count: int
    skipped_count: int
    skipped_reasons_count: Dict[str, int]
    selected: List[PoolSelectionItemV1]
    skipped: List[Dict[str, str]] # {"intent_id":..., "reason":...}
    selection_policy_v1: Dict[str, Any] # Algo config

    def to_dict(self) -> Dict[str, Any]:
        return {
            "run_id": self.run_id,
            "stage": self.stage,
            "engine_version": self.engine_version,
            "data_fingerprint": self.data_fingerprint,
            "config_signature": self.config_signature,
            "built_ts_iso": self.built_ts_iso,
            "max_open_positions": self.max_open_positions,
            "open_now": self.open_now,
            "capacity": self.capacity,
            "intents_considered": self.intents_considered,
            "intents_eligible": self.intents_eligible,
            "selected_count": self.selected_count,
            "skipped_count": self.skipped_count,
            "skipped_reasons_count": self.skipped_reasons_count,
            "selected": [s.to_dict() for s in self.selected],
            "skipped": self.skipped,
            "selection_policy_v1": self.selection_policy_v1
        }
