import json
import glob
import os
import re
from datetime import datetime

FAZ100_KEYS_FILE = "/Users/alisaglam/TezaverMac/data/faz100_dna_keys.json"
LEGACY_REPORTS = glob.glob("PURE_DNA_REPORT_*.md")
OUTPUT_FILE = "/Users/alisaglam/TezaverMac/KIYASLAMA_RAPORU_FINAL.md"

def load_faz100_strict_stats():
    with open(FAZ100_KEYS_FILE, 'r') as f:
        data = json.load(f)
        
    stats = {}
    for symbol, keys in data.items():
        # Aggregated stats for the filtered "Strict" keys
        total_signals = 0
        total_wins = 0
        t_diamond = 0
        t_loss = 0
        
        for dna, metrics in keys.items():
            s_total = metrics.get('TOTAL', 0)
            s_diamond = metrics.get('DIAMOND', 0)
            s_notier = metrics.get('NOTIER', 0)
            s_success = s_total - s_notier # Or sum tiers
            
            total_signals += s_total
            total_wins += s_success
            t_diamond += s_diamond
            t_loss += s_notier
            
        wr = (total_wins / total_signals * 100) if total_signals > 0 else 0
        stats[symbol] = {
            'wr': wr,
            'sig': total_signals,
            'diamond': t_diamond,
            'loss': t_loss
        }
    return stats

def parse_legacy_reports():
    yg_stats = {} # symbol -> {y_wr, y_sig, y_loss, g_wr, g_sig, g_loss}
    
    for rfile in LEGACY_REPORTS:
        with open(rfile, 'r') as f:
            for line in f:
                if "|" not in line or "---" in line or "Sembol" in line: continue
                parts = [p.strip() for p in line.split("|")]
                if len(parts) < 10: continue
                
                # Report Format:
                # | **COIN** | Pure... | ... | ... | Y_WR | Y_SIG | Y_LOSS | G_WR | G_SIG | G_LOSS |
                # Index 1: **Symbol**
                # Index 5: Y_WR
                # Index 6: Y_SIG
                # Index 7: Y_LOSS (🔻N)
                # Index 8: G_WR
                # Index 9: G_SIG
                # Index 10: G_LOSS (🔻N)
                
                symbol = parts[1].replace("*","").replace(" ","")
                
                # Check indices based on split length
                # split("|") on "| A | B |" gives ['', ' A ', ' B ', '']
                # Let's count properly:
                # 0: empty
                # 1: **Symbol**
                # 2: Pure WR
                # 3: Pure Sig
                # 4: Pure Diamond
                # 5: Y_WR
                # 6: Y_SIG
                # 7: Y_LOSS
                # 8: G_WR
                # 9: G_SIG
                # 10: G_LOSS
                
                # Careful with indices. Let's assume standard format generated by grand_dna_extractor_pure.py
                
                y_wr = parts[5]
                y_sig = parts[6]
                y_loss = parts[7]
                
                g_wr = parts[8]
                g_sig = parts[9]
                g_loss = parts[10]
                
                yg_stats[symbol] = {
                    'y_wr': y_wr, 'y_sig': y_sig, 'y_loss': y_loss,
                    'g_wr': g_wr, 'g_sig': g_sig, 'g_loss': g_loss
                }
    return yg_stats

def generate_final_report():
    f100_stats = load_faz100_strict_stats()
    yg_stats = parse_legacy_reports()
    
    # Get all symbols (union)
    all_symbols = sorted(list(set(f100_stats.keys()) | set(yg_stats.keys())))
    
    lines = []
    lines.append("# 🦅 FAZ-100 (SNIPER) vs MEVCUT STRATEJİLER (KIYASLAMA)")
    lines.append(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    lines.append("\n**Not:** Faz-100 (Sniper) stratejisinde 'Kayıp' oranı çok düşüktür. Sarı/Yeşil listede ise 'Filtre Kayıpları' (İyi sinyali kaçırma) veya 'Stop Olma' durumları listelenmiştir.")
    lines.append("\n| Coin | 🦅 F100 (Sniper) | | | | 🟡 SARI LİSTE | | | 🟢 YEŞİL LİSTE | | |")
    lines.append("|---|---|---|---|---|---|---|---|---|---|---|")
    lines.append("| **Sembol** | **WR%** | **Sinyal** | **💎Elmas** | **🔴Kayıp** | **WR** | **Sinyal** | **🔻Kayıp** | **WR** | **Sinyal** | **🔻Kayıp** |")
    lines.append("|---|---|---|---|---|---|---|---|---|---|---|")
    
    for sym in all_symbols:
        f100 = f100_stats.get(sym, {'wr': 0, 'sig': 0, 'diamond': 0, 'loss': 0})
        yg = yg_stats.get(sym, {'y_wr': '-', 'y_sig': '0', 'y_loss': '-', 'g_wr': '-', 'g_sig': '0', 'g_loss': '-'})
        
        # Formatting F100
        f_wr_str = f"%{f100['wr']:.1f}" if f100['sig'] > 0 else "-"
        f_dia_icon = f"💎{f100['diamond']}" if f100['diamond'] > 0 else "-"
        f_loss_icon = f"🔴{f100['loss']}"
        
        # Formatting YG (already strings in MD parse, but let's ensure consistency)
        
        line = f"| **{sym}** | {f_wr_str} | {f100['sig']} | {f_dia_icon} | {f_loss_icon} | {yg['y_wr']} | {yg['y_sig']} | {yg['y_loss']} | {yg['g_wr']} | {yg['g_sig']} | {yg['g_loss']} |"
        lines.append(line)
        
    with open(OUTPUT_FILE, 'w') as f:
        f.write("\n".join(lines))
        
    print(f"✅ Final Comparison Report saved: {OUTPUT_FILE}")

if __name__ == "__main__":
    generate_final_report()
