# Matrix V2 Core Types
"""
Core type definitions for Matrix v2 trading system.
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Literal


@dataclass
class MarketSignal:
    """
    Represents a market signal generated by an Analyzer.
    
    Contains information about detected market conditions or patterns
    that may lead to trading decisions.
    """
    signal_id: str
    symbol: str
    timeframe: str
    signal_type: str  # e.g., "rally_start", "trend_reversal", "breakout"
    direction: Literal["long", "short", "neutral"]
    confidence: float  # 0.0 to 1.0
    timestamp: datetime
    metadata: dict[str, object] = field(default_factory=dict)


@dataclass
class TradeDecision:
    """
    Represents a trading decision made by a Strategist.
    
    Contains the specific action to take based on a market signal,
    including entry/exit parameters.
    """
    decision_id: str
    signal_id: str
    symbol: str
    timeframe: str
    action: Literal["open_long", "open_short", "close", "hold"]
    entry_price: float | None = None
    stop_loss: float | None = None
    take_profit: float | None = None
    position_size: float | None = None
    reason: str = ""
    metadata: dict[str, object] = field(default_factory=dict)


@dataclass
class ExecutionReport:
    """
    Represents the result of executing a trade decision.
    
    Contains confirmation details and actual execution values.
    """
    execution_id: str
    decision_id: str
    symbol: str
    status: Literal["filled", "partial", "rejected", "pending"]
    executed_price: float | None = None
    executed_quantity: float | None = None
    commission: float = 0.0
    timestamp: datetime = field(default_factory=datetime.now)
    error_message: str | None = None
    metadata: dict[str, object] = field(default_factory=dict)


@dataclass
class MatrixEventLogEntry:
    """
    Represents a single event in the Matrix event log.
    
    Used for audit trail and debugging purposes.
    """
    event_id: str
    profile_id: str
    event_type: str  # e.g., "signal", "decision", "execution", "guardrail"
    timestamp: datetime
    payload: dict[str, object] = field(default_factory=dict)
    severity: Literal["info", "warning", "error"] = "info"
